import Header from './components/ads/Header';
import Navbar from './components/layout/Navbar';
import { Source_Serif_4 } from 'next/font/google';

import './global.css';

const sourceSerif = Source_Serif_4({
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata = {
  title: 'CRM – Labs59',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`overscroll-none ${sourceSerif.className}`}>
      <body>
        <Header />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
